### ISSUE TITLE
clone下来后第一遍正常，运行第二遍generate_training_data.py就报错了，什么都没改

### ISSUE THREAD

**Issue by OMonkey** [zezhishao/BasicTS#90] opened 2023-11-15 08:26 UTC
Traceback (most recent call last):
  File "generate_training_data.py", line 12, in <module>
    from basicts.data.transform import standard_transform
  File "/nfs/project/chenao/pythonProject/idt_predict/BasicTSCode/basicts/__init__.py", line 2, in <module>
    from .runners import BaseRunner
  File "/nfs/project/chenao/pythonProject/idt_predict/BasicTSCode/basicts/runners/__init__.py", line 2, in <module>
    from .base_tsf_runner import BaseTimeSeriesForecastingRunner
  File "/nfs/project/chenao/pythonProject/idt_predict/BasicTSCode/basicts/runners/base_tsf_runner.py", line 11, in <module>
    from ..data import SCALER_REGISTRY
  File "/nfs/project/chenao/pythonProject/idt_predict/BasicTSCode/basicts/data/__init__.py", line 12, in <module>
    scan_modules(project_dir, __file__, ["__init__.py", "registry.py"])
  File "/home/luban/anaconda3/lib/python3.8/site-packages/easytorch/utils/registry.py", line 109, in scan_modules
    return [importlib.import_module(f'{import_prefix}.{file_name}') for file_name in model_file_names]
  File "/home/luban/anaconda3/lib/python3.8/site-packages/easytorch/utils/registry.py", line 109, in <listcomp>
    return [importlib.import_module(f'{import_prefix}.{file_name}') for file_name in model_file_names]
  File "/home/luban/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'basicts.data.'

**Comment by zezhishao** [comment] 2023-11-30 03:07
I can't reproduce this error. Is there any more information?

**Comment by yuqinie98** [comment] 2024-01-24 08:09
This seems to be an issue with easytorch. You can try to delete all the "__pycache__" and ".ipynb_checkpoints" folders in the directories.

**Comment by zezhishao** [comment] 2024-01-24 08:36
> This seems to be an issue with easytorch. You can try to delete all the "__ pycache __" and ".ipynb_checkpoints" folders in the directories.

Thanks for the clue, is there any way to reproduce it?

**Comment by yuqinie98** [comment] 2024-01-24 08:46
> > This seems to be an issue with easytorch. You can try to delete all the "__ pycache __" and ".ipynb_checkpoints" folders in the directories.
> 
> Thanks for the clue, is there any way to reproduce it?

I met the same problem when using jupyterlab terminal. I modified some files in basicts/data and saved the changes, which I believe impacted the cache in some way. Then I saw this bug.

**Comment by zezhishao** [comment] 2024-01-24 08:52
Thanks for the details! I'll try to fix it later.

**Comment by yuqinie98** [comment] 2024-01-24 08:57
> Thanks for the details! I'll try to fix it later.

No problem. Thanks for fixing!

**Comment by zezhishao** [comment] 2024-01-25 04:37
Hi everyone, thank you for your suggestions. This issue should have been fixed in the latest commit [0af86ed](https://github.com/zezhishao/BasicTS/commit/0af86edb65cceee2797e4274226461d3ead2d16c).

**Comment by yuqinie98** [comment] 2024-01-25 05:25
Now it works well, thanks!

**Closed** 2024-01-25 07:23 UTC

**Comment by huiguhean** [comment] 2024-08-30 07:04
在运行METR-LR的generate_train_data.py遇到了差不多的问题
FileNotFoundError: File datasets/raw_data/METR-LA/METR-LA.h5 does not exist
我觉得大概是sys.path.append(os.path.abspath(__file__ + "/../../../.."))这一行没有起作用
当我自己手动修改    
    OUTPUT_DIR = "datasets/" + DATASET_NAME
    DATA_FILE_PATH = "datasets/raw_data/{0}/{0}.h5".format(DATASET_NAME)
    GRAPH_FILE_PATH = "datasets/raw_data/{0}/adj_{0}.pkl".format(DATASET_NAME)使用绝对路径时能正常产生
但是当我接着运行train时，遇到了找不到文件的问题，我没找到应该在哪修改文件路径
